### ISSUE TITLE
Variable CSA response curve

### ISSUE THREAD

**Issue by stephanlachnit** [allpix-squared/allpix-squared#17]
@simonspa I'm working on writing a simulation for the MuPix10 with Allpix-Squared. We have a CSA, but the impulse response curve doesn't look like the one from the CSADigitizer module, it falls linearly. A possible parameterization is `A * (1-exp(-x/tauR_) ) - tauLinearF * x`, and `0` when when the linear part becomes larger than the exponential one.

My question is what the best way is to implement this, if we want to upstream it. My idea was to add a new model (so that there would be `simple`, `csa` and `mupix`). However, this would require a model-dependent impulse response here:
https://github.com/allpix-squared/allpix-squared/blob/8e36b5156dd16f4db5d64751f91109e815ff5bb5/src/modules/CSADigitizer/CSADigitizerModule.cpp#L189-L197

Since it's only called once I don't see a big problem there. Let me know what you think. Also, the documentation for the module would require some rewriting.

**Comment by simonspa** [comment]
Hej @stephanlachnit 

and alternative we could dig into is using a `ROOT::TF1`: https://root.cern/doc/master/classTF1.html

With that approach we could allow the user to add an arbitrary response function, not limiting it to individual implementations. The parameters of the function could be provided as parameter array to be read with `config.getArray<double>()`.

What do you think?

/Simon

**Comment by stephanlachnit** [comment]
Sounds much more reasonable! Will try to implement that.
